### ISSUE TITLE
can not reproduce the results

### ISSUE THREAD

**Issue by AlbertZhangHIT** [vegarant/Invfool#1]
Hi Vargard,
Have you ever trained the networks by yourself and then tried to produce these adversarial images by your algorithm? Unfortunately, I failed to reproduce those adversarial images and unphysical results like you reported through the pre-trained FBPNet and my dataset.
Any suggestions will be appreciated.

**Comment by vegarant** [comment]
Hi Hao,

For the FBPConvNet experiments we used the pretrained networks provided by Jin et al. from the paper "Deep convolutional neural network for inverse problems in imaging".

If I read your question correctly, you have trained a network yourself on your own data and are unable to find a tiny perturbation for which find the output of the network unphysical? 

In my experience, it is possible to train poorly preforming networks, which are completely stable w.r.t. tiny perturbations. The problem with these is that the image quality is substantially worse than a comparison with state-of-the-art. Often the networks will be able to pass the tiny perturbation test, but be unable to capture details. The third test one could run on a FBPConvNet, is stability w.r.t. changing sampling rate. 

Best,
Vegard

**Comment by AlbertZhangHIT** [comment]
Hi Vegard,

Did you mean if the FBPConvNet that was trained on my own dataset is stable w.r.t. changing sampling rate in tests, it means the FBPConvNet is trained poorly?
I plotted the snr values of the reconstruction w.r.t different sampling rate, where the FBPConvNet was traind for 50 views.
![snrs](https://user-images.githubusercontent.com/29504198/56536059-02110f80-6512-11e9-860d-1468bce0a7d1.png)


Best regard,
Hao

**Comment by vegarant** [comment]
Hi,
sorry for the confusion. No I did not mean that. What I am saying is that the test consists of three parts; (1) stability w.r.t. tiny perturbations, (2) ability to capture a small structural change (important to test against state-of-the-art, to check that you are not targeting an ill posted inverse problem) and (3) stability w.r.t to changing the sampling rate. Where the third test does not apply to all network architectures.

I my experience a network might pass test (1), but then it usually fails test (2), or (3). 

Best,
Vegard

**Comment by AlbertZhangHIT** [comment]
Thank you very much for the elaboration on it. It maybe extremely hard for the networks to pass all of these tests I think.

Regards,
Hao
