### ISSUE TITLE
Missing data

### ISSUE THREAD

**Issue by martinhelso** [vegarant/Invfool#2]
The link [http://folk.uio.no/vegarant/123/storage2.zip](http://folk.uio.no/vegarant/123/storage2.zip) to the data is not working.

**Comment by vegarant** [comment]
Dear Martin,

Thank you for notifying me. My old server has been closed. I have updated the README.md with a new link to the data.

Best regards,
Vegard

**Comment by hhapk** [comment]
Dear vegarant,
The link https://www.mn.uio.no/math/english/people/aca/vegarant/data/storage2.zip  to the data is not working.
